import React from "react";
import {
  List,
  Datagrid,
  TextField,
  DateField,
  EditButton,
  Edit,
  Create,
  SimpleForm,
  TextInput,
} from "react-admin";

export const AuthorList = (props) => (
  <List {...props}>
    <Datagrid rowClick="edit">
      <TextField source="author_id" label="Author ID" />
      <TextField source="author_name" label="Author Name" />
      <TextField source="biography" label="Biography" />
      <DateField source="created_at" label="Created At" />
      <EditButton />
    </Datagrid>
  </List>
);

export const AuthorEdit = (props) => (
  <Edit {...props}>
    <SimpleForm>
      <TextInput disabled source="author_id" label="Author ID" />
      <TextInput source="author_name" label="Author Name" />
      <TextInput multiline source="biography" label="Biography" />
      <DateField source="created_at" label="Created At" />
    </SimpleForm>
  </Edit>
);

export const AuthorCreate = (props) => (
  <Create {...props}>
    <SimpleForm>
      <TextInput source="author_name" label="Author Name" />
      <TextInput multiline source="biography" label="Biography" />
      {/* The created_at field is usually auto-generated by the server */}
    </SimpleForm>
  </Create>
);
