import React from "react";
import EditAuthor from "../pages/EditAuthor";
import {
  List,
  Datagrid,
  TextField,
  DateField,
  EditButton,
  Edit,
  Create,
  SimpleForm,
  TextInput,
} from "react-admin";

export const AuthorList = (props) => (
  <List {...props}>
    <Datagrid rowClick="edit">
      <TextField source="author_id" label="Author ID" />
      <TextField source="author_name" label="Author Name" />
      <DateField source="Created_at" label="Created At" />
      <EditButton />
    </Datagrid>
  </List>
);

export const AuthorEdit = (props) => {
  return <EditAuthor />;
};

export const AuthorCreate = (props) => (
  <Create {...props}>
    <SimpleForm>
      <TextInput source="author_name" label="Author Name" />
      {/* The created_at field is usually auto-generated by the server */}
    </SimpleForm>
  </Create>
);
