import React from "react";
import EditVoucher from "../pages/EditVoucher";
import {
  List,
  Datagrid,
  TextField,
  NumberField,
  DateField,
  EditButton,
  Edit,
  SimpleForm,
  TextInput,
  NumberInput,
  Create,
} from "react-admin";

export const VoucherList = (props) => (
  <List {...props}>
    <Datagrid rowClick="edit">
      <TextField source="voucher_id" label="Voucher ID" />
      <NumberField source="quantity" label="Quantity" />
      <TextField source="detail" label="Detail" />
      <NumberField source="discount" label="Discount" />
      <DateField source="created_at" label="Created At" />
      <TextField source="used_user" label="Used User" />
      <EditButton />
    </Datagrid>
  </List>
);

export const VoucherEdit = () => {
  return <EditVoucher />;
};

export const VoucherCreate = (props) => (
  <Create {...props}>
    <SimpleForm>
      <TextInput source="voucher_id" label="Voucher ID" />
      <NumberInput source="quantity" label="Quantity" />
      <TextInput source="detail" label="Detail" />
      <NumberInput source="discount" label="Discount" />
      <TextInput source="used_user" label="Used User" />
      {/* Leave created_at out if it's auto-generated by the server */}
    </SimpleForm>
  </Create>
);
